use choose_your_story;

/* Usuario de prueba */
INSERT INTO USERS (username, password, created_by)
VALUES ('Tester', 'Passw0rd!', CURRENT_USER());

/* Personajes */
INSERT INTO CHARACTERS (name, created_by)
VALUES
('Stanley', CURRENT_USER()),
('Daniel', CURRENT_USER()),
('Felipe VI', CURRENT_USER()),
('Makoke', CURRENT_USER()),
('Jordi Garcia', CURRENT_USER()),
('Celeste', CURRENT_USER());

/* Aventuras */
INSERT INTO ADVENTURE (name, description, created_by)
VALUES
('The Stanley Parable: Terminal Edition', 'Esta es la historia de un hombre.', CURRENT_USER()),
('La llamada en la oscuridad', 'Una llamada en mitad de la noche rompe la calma y arrastra a $NAME a una cadena de decisiones imposibles. Vampiros, secretos familiares y alianzas inesperadas marcarán el camino. Cada elección puede acercarte a la verdad… o a un final fatal.', CURRENT_USER());

/* Personajes-Aventura */
INSERT INTO CHARACTER_ADVENTURE (id_character, id_adventure, created_by)
VALUES
(1,1,CURRENT_USER()),
(2,1,CURRENT_USER()),
(3,1,CURRENT_USER()),
(4,1,CURRENT_USER()),
(4,2,CURRENT_USER()),
(5,2,CURRENT_USER()),
(6,2,CURRENT_USER());

SET FOREIGN_KEY_CHECKS = 0;

/* Pasos (1, 'description', FALSE, FALSE, next_step, CURRENT_USER()), */
INSERT INTO ADVENTURE_STEP (id_adventure, description, first_step, final_step, next_step, created_by)
VALUES
(1, 'Narrador: $NAME trabajaba para una empresa en un gran edificio, donde era el empleado número 427. El trabajo del empleado número 427 era sencillo. Se sentaba en su escritorio, en la sala 427, y pulsaba teclas en un teclado. Las órdenes le llegaban a través de un monitor situado en su escritorio, que le indicaba qué teclas pulsar, durante cuánto tiempo y en qué orden. Esto es lo que el empleado 427 hacía todos los días de todos los meses de todos los años. Y aunque otros pudieran considerarlo desgarrador, $NAME disfrutaba cada momento en que llegaban las órdenes, como si hubiera sido creado precisamente para ese trabajo. Y $NAME, era feliz.', TRUE, FALSE, 2, CURRENT_USER()),
(1, 'Narrador: Y entonces, un día, ocurrió algo muy peculiar. Algo que cambiaría para siempre a $NAME. Algo que nunca olvidaría. Llevaba casi una hora sentado en su escritorio cuando se dio cuenta de que no había llegado ni una sola orden al monitor para que él la siguiese. Nadie había aparecido para darle instrucciones, convocar una reunión o siquiera saludarle. En todos sus años en la empresa nunca había ocurrido algo así, ese aislamiento total. Era evidente que algo iba muy mal. Conmocionado, paralizado, $NAME se encontró incapaz de moverse durante un buen rato. Pero cuando recuperó el juicio y los sentidos, se levantó de su escritorio y salió de su oficina.', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'Narrador: ¿Y si tuviera que tomar una decisión? ¿Y si un resultado crucial recayera bajo su responsabilidad? ¡Nunca le habían entrenado para eso! No, esto solo podía salir mal. Lo que hay que hacer ahora, pensó $NAME para sí mismo, es esperar. Nada me hará daño. Nada me quebrará. Aquí puedo ser feliz, para siempre. Seré feliz.', FALSE, FALSE, 4, CURRENT_USER()),
(1, 'Narrador: $NAME esperó. Pasaron las horas. Luego los días. ¿Habían pasado años? Ya no tenía la capacidad de saberlo. Pero lo único que sabía con certeza, sin lugar a dudas, era que si esperaba lo suficiente, las respuestas llegarían. Eventualmente, algún día, llegarían. Pronto, muy pronto, esto terminará. Le hablarán. Le dirán qué hacer. Ahora está un poco más cerca. Ahora está aún más cerca. Ya viene.', FALSE, TRUE, NULL, CURRENT_USER()),
(1, 'Narrador: Cuando $NAME llegó a un conjunto de dos puertas abiertas, entró por la puerta de la izquierda.', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'Narrador: Al llegar a una escalera, $NAME subió las escaleras hasta la oficina de su jefe.', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'Narrador: Consideró la posibilidad de enfrentarse a su jefe y admitir que había abandonado su puesto durante el horario laboral. Podrían despedirlo por eso. Y en una economía tan competitiva, ¿por qué correría ese riesgo? ¿Todo porque creía que todo el mundo había desaparecido? Su jefe pensaría que estaba loco.', FALSE, FALSE, 8, CURRENT_USER()),
(1, 'Narrador: Y entonces algo pasó por la cabeza de $NAME. Quizás..., pensó para sí mismo. Quizás estoy loco... ¿Todos mis compañeros de trabajo desapareciendo misteriosamente en un instante sin motivo alguno? Nada de eso tenía sentido desde cualquier punto de vista lógico.', FALSE, FALSE, 9, CURRENT_USER()),
(1, 'Narrador: Y mientras $NAME reflexionaba sobre esto, comenzó a hacer otras observaciones extrañas. Por ejemplo, ¿por qué no podía ver su propio cuerpo? ¿Por qué no podía volver hacia atrás en sus acciones dondequiera que fuera? Y, por cierto, esta secuencia estaba empezando a ser demasiado larga. ¿Esto tenía algún fin? No, se dijo $NAME. Todo esto es demasiado extraño, no puede ser real. Y, por fin, llegó a la conclusión que tenía en la punta de la lengua. Simplemente no había encontrado las palabras para expresarla.', FALSE, FALSE, 10, CURRENT_USER()),
(1, 'Narrador: ¡Estoy soñando!, gritó. ¡Todo esto es un sueño!. Qué alivio sintió $NAME al haber encontrado por fin una respuesta, una explicación. Sus compañeros de trabajo no habían desaparecido, no iba a perder su empleo, ¡al fin y al cabo no estaba loco! Y pensó para sí mismo: Supongo que pronto me despertaré. Tendré que volver a mi aburrido trabajo real apretando botones, así que más vale que disfrute de esto mientras aún estoy lúcido. ', FALSE, FALSE, 11, CURRENT_USER()),
(1, 'Narrador: Así que se imaginó volando y comenzó a flotar suavemente sobre el suelo. Luego se imaginó surcando el espacio en un mágico campo de estrellas, ¡y también apareció! Era muy divertido, y $NAME se maravillaba de que aún no se hubiera despertado. ¿Cómo era posible que siguiera tan lúcido? Y entonces, quizá la pregunta más extraña de todas se le ocurrió a $NAME. Una pregunta que le sorprendía no haberse hecho antes.', FALSE, FALSE, 12, CURRENT_USER()),
(1, 'Narrador: ¿Por qué hay una voz en mi cabeza que narra todo lo que hago y pienso? Ahora la voz se describía a sí misma siendo considerada por $NAME, quien lo encontraba particularmente extraño. Estoy soñando con una voz que me describe pensando en cómo es describir mis pensamientos, pensó. Y aunque le parecía muy extraño y se preguntaba si esa voz les hablaba a todas las personas en sus sueños, la verdad era que, por supuesto, no se trataba de un sueño. ¿Cómo podría serlo? ¿Acaso $NAME se estaba engañando a sí mismo? ¿Creía que, si estaba dormido, no tenía que asumir la responsabilidad de sus actos? $NAME estaba tan despierto en ese momento como lo había estado siempre en su vida.', FALSE, FALSE, 13, CURRENT_USER()),
(1, 'Narrador: Oír la voz pronunciar esas palabras fue toda una sorpresa para $NAME. Después de todo, él sabía con certeza, sin lugar a dudas, que se trataba de un sueño. ¿Acaso la voz no lo había visto flotar y crear estrellas mágicas hacía solo un momento? ¿De qué otra forma podría explicar todo eso la voz? Esa voz también formaba parte de él, sin duda, sin duda, si tan solo pudiera...', FALSE, FALSE, 14, CURRENT_USER()),
(1, 'Narrador: Lo demostraría. Demostraría que tenía el control, que todo era un sueño. Así que cerró los ojos suavemente y se invitó a sí mismo a despertar. Sintió el peso fresco de la manta sobre su piel, la presión del colchón sobre su espalda, el aire fresco de un mundo fuera de este. Déjame despertar, pensó para sí mismo... He terminado con este sueño, deseo que termine... Déjame volver a mi trabajo, déjame seguir pulsando botones, por favor, es lo único que quiero... Quiero mi apartamento, a mi mujer y mi trabajo... Lo único que quiero es que mi vida siga exactamente como siempre ha sido... Mi vida es normal, yo soy normal... Todo irá bien... Estoy bien...', FALSE, FALSE, 15, CURRENT_USER()),
(1, 'Narrador: $NAME comenzó a gritar. ¡Por favor, que alguien me despierte! ¡Me llamo $NAME! ¡Tengo un jefe! ¡Tengo una oficina! ¡Soy real! ¡Por favor, que alguien me diga que soy real! ¡Tengo que ser real! ¡Tengo que serlo! ¿Alguien puede oír mi voz? ¿Quién soy? ¿Quién soy? Y todo se volvió negro...', FALSE, FALSE, 16, CURRENT_USER()),
(1, '...', FALSE, FALSE, 17, CURRENT_USER()),
(1, 'Narrador: Esta es la historia de una mujer llamada Mariella.', FALSE, FALSE, 18, CURRENT_USER()),
(1, 'Narrador: Mariella se despertó un día como cualquier otro. Se levantó, se vistió, preparó sus cosas y se dirigió a su trabajo. Pero ese día en particular, su camino se vio interrumpido por el cuerpo de un hombre que había deambulado por la ciudad hablando y gritando solo y que luego había caído muerto en la acera. Y aunque pronto se daría la vuelta para llamar a una ambulancia, durante unos breves instantes se detuvo a observar al extraño hombre. ', FALSE, FALSE, 19, CURRENT_USER()),
(1, 'Narrador: Era obvio que estaba loco; eso lo tenía claro. Todo el mundo sabe cómo son los locos. Y en ese momento, pensó para sí misma lo afortunada que era por ser normal. Estoy cuerda. Tengo el control de mi mente. Sé lo que es real y lo que no lo es. Era reconfortante pensar eso y, en cierto modo, ver a ese hombre la hacía sentir mejor. Pero entonces recordó la reunión que tenía programada para ese día, con personas muy importantes cuya impresión sobre ella afectaría a su carrera y, por extensión, al resto de su vida. No tenía tiempo para eso, así que solo se quedó allí un momento, mirando el cuerpo. Y luego se dio la vuelta, y echó a correr.', FALSE, TRUE, NULL, CURRENT_USER()),
(1, 'Narrador: Conmocionado y desconcertado, $NAME se preguntaba incrédulo quién había orquestado todo aquello. ¿Qué oscuro secreto le estaban ocultando? Lo que no podía saber era que el teclado de acceso situado detrás del escritorio de su jefe guardaba la terrible verdad que este le había estado ocultando. Por eso, el jefe le había asignado un número PIN super secreto.', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'Narrador: 2 - 8 - 4 - 5. Pero, por supuesto, $NAME no podía saberlo de ninguna forma.', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'Narrador: Intentar introducir cualquier cosa en el dispositivo era inútil, ya que nunca podría saber que la combinación era: 2 - 8 - 4 - 5.', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'Narrador: Si supiera que la combinación era 2 - 8 - 4 - 5, sería otra historia completamente diferente.', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'Narrador: Porque el código correcto era...', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'Narrador: Si hubieras esperado un momento, te habría dicho que la combinación correcta era...', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'Narrador: Sintiéndose tranquilo y rejuvenecido, $NAME avanzó con calma hacia el pasillo abierto.', FALSE, FALSE, 27, CURRENT_USER()),
(1, 'Narrador: Al descender más profundamente en el edificio, $NAME se dio cuenta de que se sentía un poco extraño. Era una emoción que le removía el pecho, como si se sintiera más libre para pensar por sí mismo, para cuestionar la naturaleza de su trabajo. ¿Por qué sentía eso ahora, cuando durante años nunca se le había ocurrido? Esta pregunta no tardaría en tener respuesta.', FALSE, FALSE, 28, CURRENT_USER()),
(1, 'Narrador: $NAME siguió adelante y atravesó la gran puerta en la que se leía: Instalaciones de control mental.', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'Narrador: La puerta detrás de él no estaba cerrada. $NAME todavía tenía todas las oportunidades para dar media vuelta y volver al buen camino.', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'Por donde vas?', FALSE, FALSE, NULL, CURRENT_USER()),
(1, '*Llegas hasta el final del pasillo y atraviesas una puerta de luces rojas. Al atravesarla caes por un agujero en el suelo y aterrizas en una cinta que se dirige hacia una prensa mecánica en funcionamiento. Ves como otras cosas están siendo aplastadas delante de ti.*', FALSE, FALSE, 32, CURRENT_USER()),
(1, 'Narrador: Mientras la máquina se ponía en marcha y $NAME se acercaba cada vez más a su fin, reflexionó sobre cómo su vida no había tenido ninguna importancia. $NAME no es capaz de ver el panorama general. No conoce la verdadera historia. Está atrapado para siempre en su estrecha visión de lo que es este mundo. Quizás su muerte no supuso una gran pérdida, como arrancarle los ojos a un ciego. Así que se resignó y aceptó de buen grado este violento final para su breve y superficial vida. Adiós, $NAME.', FALSE, FALSE, 33, CURRENT_USER()),
(1, '*Llega tu turno, la máquina está agarrando impulso para aplastarte y... Se detiene en el último instante.*', FALSE, FALSE, 34, CURRENT_USER()),
(1, 'Narradora: Adiós, $NAME, gritó el narrador, mientras $NAME era conducido indefenso hacia las enormes mandíbulas metálicas. En un solo instante visceral, $NAME fue aniquilado cuando la máquina le aplastó todos los huesos del cuerpo, matándolo al instante. *Se abre una escotilla bajo tus pies y caes en un pasillo.*', FALSE, FALSE, 35, CURRENT_USER()),
(1, 'Narradora: Y, sin embargo, solo pasarían unos minutos antes de que $NAME reiniciara el juego, de vuelta en su oficina, tan vivo como siempre. ¿Qué pensaba exactamente el narrador que iba a conseguir?', FALSE, FALSE, 36, CURRENT_USER()),
(1, 'Narradora: Cuando todos los caminos que puedes recorrer han sido creados para ti con mucha antelación, la muerte pierde su significado, y la vida también. ¿Lo ves ahora? ¿Ves que $NAME ya estaba muerto desde el momento en que pulsó Play?', FALSE, FALSE, 37, CURRENT_USER()),
(1, 'Narradora: *risas* Oh, mira a estos dos. Cómo desean destruirse el uno al otro. Cómo desean controlarse el uno al otro. Cómo ambos desean ser libres. ¿Lo ves? ¿Ves cuánto se necesitan el uno al otro? No, quizá no. A veces estas cosas no se pueden ver. Pero escúchame, aún puedes salvar a estos dos. Puedes detener el programa antes de que ambos fracasen.', FALSE, FALSE, 38, CURRENT_USER()),
(1, '*Eres traído de vuelta al momento en el que estabas en la cinta transportadora de antes. Está todo como comenzó, dirigiéndote hacia la prensa mecánica lentamente.*', FALSE, FALSE, 39, CURRENT_USER()),
(1, 'Narradora: Haz Ctrl+C y detén el programa. No hay otra forma de ganar este juego. Mientras sigas adelante, estarás recorriendo el camino de otra persona. Detente ahora, y esa será tu única opción verdadera. *Te acercas cada vez más a la prensa.* Hagas lo que hagas, ¡elige! ¡No dejes que el tiempo elija por ti! No dejes que el tiempo eli-', FALSE, FALSE, 40, CURRENT_USER()),
(1, '[Mueres aplastado brutalmente por la prensa mecánica]', FALSE, TRUE, NULL, CURRENT_USER()),
(1, 'Narrador: ¿Qué horrible secreto escondía este lugar?, pensó $NAME para sí mismo. ¿Tenía la fuerza necesaria para descubrirlo?', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'Narrador: Cada uno llevaba el número de un empleado del edificio: los compañeros de trabajo de $NAME. Las vidas de tantas personas reducidas a imágenes en una pantalla, y $NAME era una de ellas, vigilado eternamente en este lugar donde la libertad no significaba nada.', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'Narrador: ¿$NAME había estado realmente bajo el control de alguien todo este tiempo? ¿Era esa la única razón por la que estaba contento con su aburrido trabajo? ¿Que sus emociones habían sido manipuladas para aceptarlo ciegamente?', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'Narrador: ¿Su propia vida controlada por otra persona? ¡Nunca! Era impensable, ¿verdad? ¿Era siquiera posible? ¿Realmente había pasado toda su vida completamente ciego al mundo?', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'Narrador: Controles etiquetados con emociones: feliz, triste o satisfecho. Caminar, comer, trabajar; todo ello supervisado y controlado desde este mismo lugar. Y a medida que la fría realidad de su pasado comenzaba a calar en él, $NAME decidió que esta maquinaria nunca volvería a ejercer su terrible poder sobre otra vida humana. Porque él desmantelaría los controles de una vez por todas.', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'En una gran pantalla se lee: CONTROL MENTAL INACTIVO... A LA ESPERA DE ENTRADA...', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'Narrador: Después de mantenerte esclavizado todos estos años, vas y tratas de tomar el control de la máquina por ti mismo, ¿es eso lo que querías? ¿Control? Oh... $NAME. *suspiro* Aplaudo tu esfuerzo, de verdad, pero tienes que entender que hay un límite en lo que esa máquina puede hacer. Se suponía que debías dejarlo ir, apagar los controles y marcharte. ', FALSE, FALSE, 48, CURRENT_USER()),
(1, 'Narrador: Si quieres desbaratar mi historia, tendrás que esforzarte mucho más. Me temo que no tienes ni de lejos el poder que crees tener; por ejemplo, y creo que esto te resultará pertinente: $NAME se dio cuenta de repente de que acababa de activar el sistema de detonación de emergencia de la red. En caso de que esta máquina se active sin la identificación de ADN adecuada, los detonadores nucleares están programados para explotar, eliminando todo el complejo. ¿Cuánto tiempo falta para la detonación? Hmm... digamos que... dos minutos. ', FALSE, FALSE, 49, CURRENT_USER()),
(1, 'Narrador: Ah, ahora esto se está poniendo un poco más divertido, ¿no es así, $NAME? ¡Es tu momento de brillar! ¡Tú eres la estrella! Ahora es tu historia; dale forma según los deseos de tu corazón. ¡Oh, esto es mucho mejor de lo que tenía en mente! Qué pena que nos quede tan poco tiempo para disfrutarlo. Solo quedan unos instantes para que explote la bomba, ¡pero qué instantes tan preciosos son cada uno de ellos! Más tiempo para hablar de ti, de mí, de adónde vamos, de lo que significa todo esto... ¡Apenas sé por dónde empezar! ', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'Narrador: ¿Qué es eso? ¿Quieres saber dónde están tus compañeros de trabajo? ¿Un momento de consuelo antes de que te destruyan? Está bien. Estoy de buen humor. De todos modos vas a morir. Te diré exactamente lo que les pasó: los borré. Apagué la máquina; te liberé. Por supuesto, eso fue solo en esta versión de la historia. A veces, cuando la cuento, simplemente te dejo sentado en tu oficina para siempre, pulsando botones sin cesar y muriendo solo. Otras veces, dejo que la oficina se hunda en el suelo, tragándose a todos los que están dentro; o la dejo arder hasta quedar reducida a cenizas. ', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'Narrador: Sin embargo, tengo que decir que esta versión de los hechos ha sido bastante divertida. Ver cómo intentas darle sentido a todo y recuperar el control que te han arrebatado... es muy gratificante. ¡Casi me da pena que se acabe! Pero estoy seguro de que lo que se me ocurra en la próxima partida será aún mejor. ¡Dios mío! Solo quedan 34 segundos... ¡pero lo estoy disfrutando tanto! ¿Sabes qué? Al diablo con esto. Voy a añadir algo más de tiempo extra al reloj, ¡por qué no! ', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'Narrador: Estos son segundos adicionales preciosos, $NAME. ¡El tiempo no crece en los árboles! Oh, Dios mío, ¿qué pasa, $NAME? ¿Es que no tienes ni idea de adónde vas ni de lo que se supone que debes hacer ahora mismo? ¿O es que al ver el temporizador has dado por sentado que hay algo en esta habitación capaz de apagarlo?', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'Narrador: ¡Mírate, corriendo de botón en botón, de pantalla en pantalla, haciendo clic en cada pequeña cosa de esta habitación! ¡Estos botones con números! ¡No! ¡Estos de colores! ¡O tal vez este gran botón rojo! ¡O esta puerta! ¡Todo! ¡Cualquier cosa! ¡Algo aquí me salvará! ¿Por qué piensas eso, $NAME? ¿Que este videojuego se puede superar, ganar, resolver? ¿Tienes idea de cuál es tu propósito en este lugar? Jajaja, je, $NAME... te espera una gran decepción. ', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'Narrador: Pero aquí tienes un spoiler: ese temporizador no es un catalizador para mantener la acción en marcha. Solo son segundos que te acercan a la muerte. Sigues jugando en lugar de ver una escena automática porque quiero verte en cada momento en el que estás indefenso, sin poder, para verte humillado. Esto no es un desafío. Es una tragedia. Querías controlar este mundo; está bien. Pero yo lo destruiré primero, para que no puedas hacerlo. ', FALSE, FALSE, 55, CURRENT_USER()),
(1, 'Narrador: Echa un vistazo al reloj, $NAME. Te quedan 30 segundos para luchar. Treinta segundos hasta una gran explosión, y luego nada. Aquí no hay final, solo tú volando en pedazos. ¿Te aferrarás desesperadamente a tu frágil vida o la dejarás ir pacíficamente? ¡Otra elección! Haz que valga la pena. O no. Para mí es lo mismo. Todo forma parte de la broma. Y créeme, me reiré cada segundo de tu inevitable muerte, desde el momento en que desaparezcamos hasta el momento en que diga: Y fueron felices para siem-', FALSE, TRUE, NULL, CURRENT_USER()),
(1, '[Empieza a abrirse una compuerta gigante donde antes se encontraba la gran pantalla]', FALSE, FALSE, 57, CURRENT_USER()),
(1, 'Narrador: ¡Sí! Había ganado. Había derrotado a la máquina, se había liberado del control de otra persona. ¡La libertad estaba a solo unos instantes! Y, sin embargo, incluso mientras la inmensa puerta se abría lentamente, $NAME reflexionaba sobre cuántos enigmas quedaban aún por resolver. ¿Dónde habían ido sus compañeros de trabajo? ¿Cómo se había liberado del control de la máquina? ¿Qué otros misterios escondía ese extraño edificio? Pero, cuando la luz del sol inundó la sala, se dio cuenta de que nada de eso le importaba. Porque lo que había estado buscando no era el conocimiento, ni siquiera el poder, sino la felicidad.', FALSE, FALSE, 58, CURRENT_USER()),
(1, 'Narrador: Quizás su objetivo no era comprender, sino dejarlo ir. Ya nadie le diría adónde ir, qué hacer o cómo sentirse. Fuera cual fuera la vida que viviera, sería la suya. Y eso era todo lo que necesitaba saber. Quizás era lo único que valía la pena saber. $NAME atravesó la puerta abierta.', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'Narrador: $NAME sintió la brisa fresca sobre su piel, la sensación de liberación, la inmensa posibilidad del nuevo camino que se abría ante él. Así era exactamente como, en ese momento, debían suceder las cosas.', FALSE, FALSE, 60, CURRENT_USER()),
(1, 'Narrador: Y $NAME... fue feliz.', FALSE, TRUE, NULL, CURRENT_USER()),
(1, 'Narrador: Ah, sí. Sin duda, una habitación digna de admiración. Al fin y al cabo, había merecido la pena el desvío, solo por pasar unos momentos aquí, en esta habitación inmaculada y bellamente construida. $NAME se quedó allí de pie, absorbiéndolo todo.', FALSE, FALSE, 62, CURRENT_USER()),
(1, 'Narrador: Pero, ansioso por volver al trabajo, $NAME se desvió por la sección de mantenimiento, caminó recto hacia la puerta opuesta y volvió a la ruta correcta.', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'Narrador: Así que ahora, para volver, tenía que ir, umm... eh... tu, tu, tu, tu, tu, desde aquí es... amm... a la izquierda.', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'Narrador: Oh, no. No, es a la derecha, fallo mío.', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'Narrador: ¡No! ¡No, no, no! ¡No es la derecha! ¿Por qué habría dicho que era a la derecha? ¿En qué estaba pensando? Está claro que... Oh, Dios mío, ¿podrías esperar un momento, por favor? *ruido de papeles* A ver... fuimos, eh... a la derecha... a la izquierda... abajo... a la izquierda... a la derecha... ¡Ah, sí! ¡Vale, vale, sí! ¡Ya lo tengo! Esta historia es absolutamente, definitivamente, por aquí. ', FALSE, FALSE, NULL, CURRENT_USER()),
(1, 'Narrador: ¡NO! ¡No! ¡No, no, no, no, no, no, no! ¡Esto no está bien! ¡No deberías estar aquí todavía, esto es un spoiler! ¡Rápido, $NAME, cierra los ojos! Vale, vale, vale, vale, solo tenemos que volver a... um... oh... ¿a quién quiero engañar? Ahora todo es una basura. Toda la historia... completamente inutilizable. En lugar de perder el tiempo intentando salvar este sinsentido, ¿qué tal si reiniciamos el juego desde el principio? Y esta vez, supongamos que no nos desviamos tanto del camino, ¿eh? ¡Vale, desde el principio!', FALSE, TRUE, NULL, CURRENT_USER()),
(2, 'Estás durmiendo cuando un zumbido insistente rompe la quietud de la noche. El teléfono vibra sobre la mesita y $NAME abre los ojos a medias, aún aturdido. En la pantalla parpadea un número desconocido.', TRUE, FALSE, NULL, CURRENT_USER()),
(2, 'Al día siguiente descubres que tus padres han desaparecido... y un frío brutal te atraviesa el pecho. Todo tu mundo se desmorona en un instante.', FALSE, TRUE, NULL, CURRENT_USER()),
(2, 'La voz que escuchas es la de tu madre. Te cuenta, con la respiración agitada, que están siendo perseguidos por vampiros y no saben si podrán salir de esta. Antes de cortar, te pide que llames a tu tío.', FALSE, FALSE, NULL, CURRENT_USER()),
(2, 'Sientes como si una mirada invisible te sigue en silencio.', FALSE, FALSE, NULL, CURRENT_USER()),
(2, 'Tu tío cumple su palabra. Encuentra a tus padres antes de que sea demasiado tarde y los salva. Cuando por fin están a salvo, $NAME siente cómo la tensión por fin se rompe y puede respirar de nuevo.', FALSE, TRUE, NULL, CURRENT_USER()),
(2, 'Intentas huir, el miedo te frena. Es demasiado tarde: la sombra te alcanza y te mata.', FALSE, TRUE, NULL, CURRENT_USER()),
(2, 'Ves de golpe a un ser pálido, con colmillos y ojos rojos. Entiendes al instante que es un vampiro. Se lanza hacia ti, pero reaccionas rápido: le golpeas con el bate y sales corriendo.', FALSE, FALSE, NULL, CURRENT_USER()),
(2, 'Quedas atrapado con pocas opciones, mientras el vampiro ruge detrás de la barrera.', FALSE, FALSE, NULL, CURRENT_USER()),
(2, 'Piensas que por fin estás a salvo… pero entonces lo ves: el mismo vampiro de antes se arrodilla ante la oficial, como si la reconociera. La barrera del sótano no la detiene a ella, y en un instante te alcanza y te inmoviliza.', FALSE, TRUE, NULL, CURRENT_USER()),
(2, 'Abres el compartimiento y encuentras objetos de cazavampiros marcados con los nombres de tus padres. Entre todo eso, una lámpara mágica destaca con un brillo extraño… y algo en ella te transmite un peligro difícil de ignorar.', FALSE, FALSE, NULL, CURRENT_USER()),
(2, 'El vampiro se quedó allí, esperando pacientemente a que salieras. Al final, nunca lo hiciste. Moriste de hambre dentro de la habitación, mientras él aguardaba en silencio al otro lado.', FALSE, TRUE, NULL, CURRENT_USER()),
(2, 'El genio cumplió tu deseo. Tus padres regresaron y todos los vampiros fueron eliminados, sin importar si eran buenos o malos. Pero el precio era demasiado alto: $NAME. Desapareciste sin dejar rastro.', FALSE, TRUE, NULL, CURRENT_USER()),
(2, 'Aun así, mientras aceleras por la carretera, ves al vampiro persiguiéndote.', FALSE, FALSE, NULL, CURRENT_USER()),
(2, 'Entras en tu casa y encuentras a una mujer majestuosa sentada allí. Con solo mirar a $NAME, una fuerza invisible lo oprime. No puede resistirse y todo se apaga.', FALSE, TRUE, NULL, CURRENT_USER()),
(2, 'Te acercas a la comisaría y ves a dos oficiales en la entrada. ¿A cuál decides hablarle?', FALSE, FALSE, NULL, CURRENT_USER()),
(2, 'El hombre te pregunta qué deseas, y mientras habla notas un leve brillo rojo en sus ojos que te pone en alerta.', FALSE, FALSE, NULL, CURRENT_USER()),
(2, 'Cuando amanece, decides irte de allí, pero sabes que los vampiros seguirán persiguiéndote. Nunca volviste a saber nada de tus padres.', FALSE, TRUE, NULL, CURRENT_USER()),
(2, 'El chico mira a $NAME con calma. Se presenta como Draven y admite que es un vampiro distinto. Dice que le debe un favor a tus padres y que ayudará pase lo que pase.', FALSE, FALSE, NULL, CURRENT_USER()),
(2, 'La mujer se sorprende al verte, como si te reconociera. Te lleva a una sala vacía y de repente le brotan colmillos y los ojos se tornan rojos.', FALSE, FALSE, NULL, CURRENT_USER()),
(2, 'Te agarra del cuello y murmura que por fin podrán vengarse de sus compañeros.', FALSE, TRUE, NULL, CURRENT_USER()),
(2, 'El oficial dispara a la vampira y esta se desvanece. Luego te pregunta si tus padres son Garnu y Ale.', FALSE, FALSE, NULL, CURRENT_USER()),
(2, 'Algo cambia y pierdes el control de tu cuerpo. Todo termina en un desenlace trágico.', FALSE, TRUE, NULL, CURRENT_USER()),
(2, 'Draven lleva a $NAME con su clan. Rescatan a tus padres y vuelves a reunirte con ellos a salvo.', FALSE, TRUE, NULL, CURRENT_USER());

/* (1, 'description', FALSE, FALSE, next_step, CURRENT_USER()), */
SET FOREIGN_KEY_CHECKS = 1;

/* Respuestas (step_id, 'description', 'resolution', next_step, CURRENT_USER()), */
INSERT INTO ADVENTURE_STEP_ANSWER (id_adventure_step, description, resolution, next_step, created_by)
VALUES
(2, 'Salir de la oficina', 'Narrador: Todos sus compañeros de trabajo se habían ido. ¿Qué podía significar eso? $NAME decidió ir a la sala de reuniones; tal vez simplemente se había perdido un memorándum.', 5, CURRENT_USER()),
(2, 'Cerrar la puerta de la oficina y encerrarse en ella', 'Narrador: Pero $NAME simplemente no pudo soportar la presión.', 3, CURRENT_USER()),
(5, 'Ir por la puerta de la izquierda', 'Narrador: Sin embargo, aquí tampoco había ni una sola persona. Sintiendo una oleada de incredulidad, $NAME decidió subir a la oficina de su jefe con la esperanza de encontrar allí una respuesta.', 6, CURRENT_USER()),
(5, 'Ir por la puerta de la derecha', 'Narrador: Este no era el camino correcto hacia la sala de reuniones, y $NAME lo sabía perfectamente. Quizás quería pasar primero por la sala de descanso de los empleados, solo para admirarla.', 61, CURRENT_USER()),
(6, 'Subir por las escaleras', 'Narrador: Al entrar en la oficina de su jefe, $NAME se quedó una vez más atónito al descubrir que no había ningún indicio de vida humana.', 20, CURRENT_USER()),
(6, 'Bajar por las escaleras', 'Narrador: Pero $NAME simplemente no pudo hacerlo.', 7, CURRENT_USER()),
(20, 'Dejar que el narrador siga hablando', '', 21, CURRENT_USER()),
(20, 'Poner el código 2-8-4-5 en el teclado', 'Narrador: $NAME tenía tanta prisa por terminar la historia lo antes posible que ni siquiera tuvo un minuto para dejar hablar al narrador. Ese tipo de ansiedad no es saludable, así que se relajó unos momentos con música new age tranquilizante.', 26, CURRENT_USER()),
(20, 'Poner un número al azar en el teclado', 'Narrador: $NAME decidió que la paciencia era una virtud sobrevalorada. Antes de que el narrador pudiera siquiera acabar de hablar, $NAME aporreó agresivamente el teclado como si le debiera dinero. Naturalmente, esto no sirvió para nada.', 24, CURRENT_USER()),
(21, 'Poner combinaciones erroneas', 'Narrador: $NAME se quedó poniendo combinaciones al azar.', 22, CURRENT_USER()),
(21, 'Poner el código 2-8-4-5 en el teclado', 'Narrador: Sin embargo, increíblemente, simplemente pulsando botones al azar en el teclado, $NAME introdujo por pura suerte el código correcto. Increíble. Entró en el pasillo recién abierto.', 27, CURRENT_USER()),
(22, 'Poner más combinaciones erroneas', 'Narrador: $NAME simplemente comenzó a introducir códigos aleatorios en el teclado nuevamente, sabiendo perfectamente que era estadísticamente muy improbable que eso diera como resultado la combinación correcta.', 23, CURRENT_USER()),
(22, 'Poner el código 2-8-4-5 en el teclado', 'Narrador: Sin embargo, increíblemente, simplemente pulsando botones al azar en el teclado, $NAME introdujo por pura suerte el código correcto. Increíble. Entró en el pasillo recién abierto.', 27, CURRENT_USER()),
(23, 'Volver a poner más combinaciones incorrectas', 'Narrador: Vale, creo que a estas alturas todos sabemos cómo va a continuar la cosa. Bla, bla, bla, secretos oscuros, el teclado, $NAME pulsa algunos botones. Oh, mira, ¡es un nuevo pasadizo! Qué sorpresa.', 27, CURRENT_USER()),
(23, 'Poner el código 2-8-4-5 en el teclado', 'Narrador: Sin embargo, increíblemente, simplemente pulsando botones al azar en el teclado, $NAME introdujo por pura suerte el código correcto. Increíble. Entró en el pasillo recién abierto.', 27, CURRENT_USER()),
(24, 'Dejar que el narrador acabe de hablar', '', 21, CURRENT_USER()),
(24, 'Probar otra combinación antes de que diga nada', 'Narrador: $NAME, sin esperar ningún tipo de orientación narrativa, introdujo con confianza un código que era, en todos los sentidos imaginables, incorrecto. $NAME, me pregunto qué crees que estás tratando de lograr aquí.', 25, CURRENT_USER()),
(25, 'Dejar que el narrador acabe de hablar', '', 21, CURRENT_USER()),
(25, 'Empezar a apretar todos los botones como loco', 'Narrador: $NAME. Escúchame. Esto no está funcionando. Mira, ¿sabes qué? Aquí está la puerta, vete ya.', 27, CURRENT_USER()),
(28, 'Avanzar por la puerta', 'Narrador: Las luces se encendieron en una enorme sala repleta de pantallas de televisión.', 41, CURRENT_USER()),
(28, 'Desviarse por un pasillo que pone: ESCAPA', 'Narrador: Aunque en este pasillo había escrita la palabra ESCAPA, la verdad era que, al final de este pasillo, $NAME encontraría una muerte violenta.', 29, CURRENT_USER()),
(29, 'Continuar por el pasillo', 'Narrador: En ese momento, $NAME estaba haciendo un esfuerzo consciente y concertado por seguir adelante y afrontar voluntariamente su muerte.', 31, CURRENT_USER()),
(29, 'Salir del pasillo', 'Narrador: Pero, por supuesto, $NAME lo pensó mejor y se dio cuenta de que tenía demasiado por lo que vivir.', 30, CURRENT_USER()),
(30, 'Avanzar por la puerta', 'Narrador: Las luces se encendieron en una enorme sala repleta de pantallas de televisión.', 41, CURRENT_USER()),
(30, 'Volver al pasillo donde ponía ESCAPA', 'Narrador: Nope, sigue apostando por la muerte.', 31, CURRENT_USER()),
(41, 'Pulsar un botón con el símbolo de una cámara de vigilancia', 'Narrador: Ahora los monitores cobraron vida, revelando su verdadera naturaleza.', 42, CURRENT_USER()),
(42, 'Pulsar un botón con el símbolo de un ascensor', 'Narrador: Esta instalación de control mental... era demasiado horrible para creerlo. No podía ser verdad.', 43, CURRENT_USER()),
(43, 'Subir al ascensor que había bajado a la plataforma', 'Narrador: ¡No! Se negaba a creerlo. No podía aceptarlo.', 44, CURRENT_USER()),
(44, 'Salir del ascensor', 'Narrador: Pero aquí estaba la prueba. El corazón de la operación.', 45, CURRENT_USER()),
(45, 'Seguir explorando las instalaciones', 'Narrador: Y cuando por fin encontró la fuente del poder de la habitación, supo que era su deber, su obligación, acabar con ese horrible lugar y con todo lo que representaba.', 46, CURRENT_USER()),
(46, 'Pulsar un botón que pone ON', 'Narrador: Oh, $NAME, no habrás activado los controles, ¿verdad?', 47, CURRENT_USER()),
(46, 'Pulsar un botón que pone OFF', '*Se apagan todas las luces.* Narrador: La oscuridad... y una creciente sensación de incertidumbre... ¿Se había acabado?', 57, CURRENT_USER()),
(49, 'Pulsar un botón cyan con el símbolo de unos documentos intentando evitar que explote la bomba', '', 50, CURRENT_USER()),
(49, 'Pulsar un botón blanco con el número 1 intentando evitar que explote la bomba', '', 50, CURRENT_USER()),
(49, 'Pulsar un botón rojo con el símbolo de un triangulo intentando evitar que explote la bomba', '', 50, CURRENT_USER()),
(50, 'Pulsar un botón blanco con el número 2 intentando evitar que explote la bomba', '', 51, CURRENT_USER()),
(50, 'Pulsar un botón rojo gigante intentando evitar que explote la bomba', '', 51, CURRENT_USER()),
(50, 'Pulsar un botón amarillo con el símbolo de una bombilla intentando evitar que explote la bomba', '', 51, CURRENT_USER()),
(51, 'Pulsar un botón azul gigante intentando evitar que explote la bomba', '', 52, CURRENT_USER()),
(51, 'Pulsar un botón naranja con el símbolo de una cara triste intentando evitar que explote la bomba', '', 52, CURRENT_USER()),
(51, 'Pulsar un botón blanco con el número 3 intentando evitar que explote la bomba', '', 52, CURRENT_USER()),
(52, 'Accionar una palanca intentando evitar que explote la bomba', '', 53, CURRENT_USER()),
(52, 'Pulsar un botón blanco con el número 4 intentando evitar que explote la bomba', '', 53, CURRENT_USER()),
(52, 'Huir por una puerta cualquiera de la sala principal', '', 53, CURRENT_USER()),
(53, 'Resignarte', '', 54, CURRENT_USER()),
(53, 'Empezar a golpear ordenadores y maquinas aleatorias', '', 54, CURRENT_USER()),
(53, 'Pulsar un botón blanco con el número 5 intentando evitar que explote la bomba', '', 54, CURRENT_USER()),
(58, 'Atravesar la puerta abierta', '', 59, CURRENT_USER()),
(62, 'Seguir recto hacia la ruta correcta', 'Narrador: Como después de este desvío la oficina del jefe quedaba más cerca, $NAME decidió ir allí en busca de explicaciones.', 6, CURRENT_USER()),
(62, 'Bajar por un ascensor que se encuentra en la sala', 'Narrador: Pero $NAME no quería volver a la oficina, quería pasear y alejarse aún más del camino.', 63, CURRENT_USER()),
(63, 'Ir a la izquierda', '', 64, CURRENT_USER()),
(64, 'Ir a la derecha', '', 65, CURRENT_USER()),
(65, 'Ir por ahí', '', 66, CURRENT_USER()),
(67, 'Ignoras la llamada y vuelves a dormir.', 'La noche pasa tranquilamente.', 68, CURRENT_USER()),
(67, 'Contestas la llamada.', 'Coges el móvil, preguntándote quién llama.', 69, CURRENT_USER()),
(67, 'Ignoras la llamada pero te levantas.', 'Una inquietud te recorre el cuerpo.', 70, CURRENT_USER()),
(70, 'Decides quedarte en tu habitación.', 'Una sombra aparece en la ventana.', 72, CURRENT_USER()),
(70, 'Sales con un bate en la mano.', 'No ves nada, pero algo se esconde.', 73, CURRENT_USER()),
(70, 'Llamas a tus padres.', 'El aire se vuelve pesado.', 69, CURRENT_USER()),
(69, 'Llamas a tu tío.', 'Te promete que se encargará.', 71, CURRENT_USER()),
(73, 'Bajas al sótano.', 'Una barrera invisible protege el lugar.', 74, CURRENT_USER()),
(74, 'Llamas a la policía.', 'Una oficial aparece en la casa.', 75, CURRENT_USER()),
(74, 'Buscas algo útil.', 'Encuentras un compartimiento secreto.', 76, CURRENT_USER()),
(76, 'Frotas la lámpara.', 'Un genio aparece y cumples tu deseo.', 78, CURRENT_USER()),
(76, 'No haces nada.', 'Mueres atrapado.', 77, CURRENT_USER()),
(73, 'Vas al garaje.', 'Logras escapar en el coche.', 79, CURRENT_USER()),
(79, 'Intentas despistar al vampiro.', 'El silencio se vuelve inquietante.', 80, CURRENT_USER()),
(79, 'Vas a la comisaría.', 'Buscas ayuda desesperadamente.', 81, CURRENT_USER()),
(81, 'Hablas con el hombre pálido.', 'Algo no te da buena espina.', 82, CURRENT_USER()),
(82, 'Pides quedarte allí.', 'El oficial se marcha.', 83, CURRENT_USER()),
(82, 'Cuentas todo.', 'Escuchas un disparo.', 84, CURRENT_USER()),
(81, 'Hablas con la mujer afro.', 'Le explicas quién eres.', 85, CURRENT_USER()),
(85, 'La enfrentas con el bate.', 'No le haces daño.', 86, CURRENT_USER()),
(85, 'Gritas pidiendo ayuda.', 'El otro oficial entra.', 87, CURRENT_USER()),
(87, 'Rompes a llorar.', 'Todo termina mal.', 88, CURRENT_USER()),
(87, 'Confirmas quiénes son tus padres.', 'El oficial intenta tranquilizarte.', 84, CURRENT_USER()),
(84, 'Confías en él.', 'Te lleva con su clan.', 89, CURRENT_USER()),
(84, 'Le preguntas qué lo hace distinto.', 'Te explica su código.', 89, CURRENT_USER());

/* (step_id, 'description', 'resolution', next_step, CURRENT_USER()), */